version: '3.8'

services:
  youtube-curator-api:
    image: ghcr.io/bakkerme/youtube-curator-v2:latest
    container_name: youtube-curator-v2
    restart: unless-stopped
    environment:
      # Database configuration
      - DB_PATH=/app/youtubecurator.db
      
      # SMTP Configuration
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-your-email@example.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-your-app-password}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL:-recipient@example.com}
      
      # Optional configuration with sensible defaults
      - CHECK_INTERVAL=${CHECK_INTERVAL:-1h}
      - DEBUG_MOCK_RSS=${DEBUG_MOCK_RSS:-false}
      - DEBUG_SKIP_CRON=${DEBUG_SKIP_CRON:-false}
      - ENABLE_API=${ENABLE_API:-true}
      - API_PORT=${API_PORT:-8080}
    ports:
      - "${HOST_PORT:-8080}:8080"
    networks:
      - youtube-curator-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/channels"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  youtube-curator-frontend:
    image: ghcr.io/bakkerme/youtube-curator-v2-ui:latest
    container_name: youtube-curator-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://youtube-curator-api:8080/api}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      youtube-curator-api:
        condition: service_healthy
    networks:
      - youtube-curator-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  youtube-curator-network:
    driver: bridge 